### ISSUE TITLE
Feature: Include Depth First Search

### ISSUE THREAD

**Issue by ashikvarma11** [ashikvarma11/tree-traverse#6]
- All methods should be written in tree.model.js.
- Include algorithm for Depth first Search in tree.model.js file.
- Add button to the UI for triggering the function.

**Comment by iamsriranga** [comment]
@ashikvarma11, can I work on this

**Comment by ashikvarma11** [comment]
@saideepesh000  Yes you can start working on this.

**Comment by ashikvarma11** [comment]
@saideepesh000  Are you working on this issue? I believe all DFS algos have been implemented. You could try this issue instead. #4

**Comment by iamsriranga** [comment]
> @saideepesh000  Are you working on this issue? I believe all DFS algos have been implemented. You could try this issue instead. #4 

Yes, I'll PR by tomorrow

**Comment by ashikvarma11** [comment]
@saideepesh000  Okay.  Thanks.

**Comment by iamsriranga** [comment]
@ashikvarma11, should I alter the styling of buttons so that it looks good. like below

### BEFORE

![Screenshot (271)](https://user-images.githubusercontent.com/43727167/94934782-d1484e80-04e9-11eb-8d05-005cf0820ffb.png)



### AFTER
![Screenshot (270)](https://user-images.githubusercontent.com/43727167/94934723-bbd32480-04e9-11eb-88e5-33f94b167756.png)

**Comment by ashikvarma11** [comment]
@saideepesh000  No, let the UI be the same. We have a different issue specifically for UI changes.

**Comment by iamsriranga** [comment]
> 
> 
> @saideepesh000 No, let the UI be the same. We have a different issue specifically for UI changes.

oh ok ok
